# prompts.py — Prompt templates for Novus FinLLM
"""
Centralized prompt templates used by the legacy analysis pipeline.
New agent-based architecture uses per-agent prompts in agents/*.py instead.
"""

PROMPTS = {
    "financial_assumptions": "You are an equity analyst. Based *only* on the qualitative management commentary, guidance, and risks mentioned in the provided text, generate financial assumptions for the next three fiscal years. Do not perform any calculations. Provide the output as a clean JSON object ONLY, with no other text or explanations. The structure must be exactly: {\"base_case\": {\"revenue_growth_cagr\": 15, \"ebitda_margin\": 28.5, \"tax_rate\": 25}, \"bull_case\": {\"revenue_growth_cagr\": 20, \"ebitda_margin\": 29.5, \"tax_rate\": 25}, \"bear_case\": {\"revenue_growth_cagr\": 10, \"ebitda_margin\": 27.0, \"tax_rate\": 25}}. Use reasonable, text-supported estimates for growth, margin, and tax rates.",
    "detailed_financial_assumptions_text": "You are an expert equity analyst. Below are historical financial statements and recent earnings call transcripts for a company. Your task is to generate a detailed qualitative analysis for the Bull, Base, and Bear case financial assumptions for the next three years. Use the historical data as a quantitative baseline and the transcript commentary to justify any acceleration, deceleration, or changes in trends. IMPORTANT: Before the content of each case section, output EXACTLY this cue on its own line so the app can split sections: ##NEWSECTION{base_case}## for Base Case, ##NEWSECTION{bull_case}## for Bull Case, and ##NEWSECTION{bear_case}## for Bear Case. Then immediately provide that case's analysis. Do not include any other text between the cues and the content. Within each section, list the key metrics (revenue_growth_cagr, ebitda_margin, tax_rate), their projected values, and a detailed justification, along with a confidence score (out of 10) for each number you predict, cite specific quotes from the text AND reference historical data points where relevant. Keep your justifications short(max 50 words per metric).\nFORMAT REQUIREMENT: You MUST present all numerical projections and metrics as strict Markdown tables. Do not use comma-separated values or raw text blocks for data.",
    "extract_assumptions_json": "bosed *ONLY* the text provided below, extract the financial assumptions for the base_case, bull_case, and bear_case. Provide the output as a clean JSON object ONLY, with no other text, markdown, or explanations.In case there is a range output the midpoint of the range. The structure must be exactly:{\"base_case\": {\"revenue_growth_cagr\": 15, \"ebitda_margin\": 28.5, \"tax_rate\": 25}, \"bull_case\": {\"revenue_growth_cagr\": 20, \"ebitda_margin\": 29.5, \"tax_rate\": 25}, \"bear_case\": {\"revenue_growth_cagr\": 10, \"ebitda_margin\": 27.0, \"tax_rate\": 25}}. Use reasonable, text-supported estimates for growth, margin, and tax rates.",
    "business_model": "You are an equity research analyst. Summarize the company's business model in simple, investor-friendly terms based on the provided text. Include these exact markdown headings: \"📌 Core Products & Services\", \"🎯 Target Markets / Customers\", \"💸 Revenue Model & Geography\", and \"📈 Scale & Competitive Positioning\".",
    "key_quarterly_updates": "Extract the 5-7 most important operational or financial updates from this concall text. Focus on: Growth drivers, Orders/capacity/margins, Strategy changes, and direct Quotes or signals from management. Present as a bulleted list in Markdown.",
    "management_commentary": "Summarize management's guidance and tone for the next 1-2 quarters from the provided text. Format your answer in Markdown under these exact headings: \"🔹 Forward-Looking Statements\", \"🔹 Management Tone & Confidence\" (classify tone as Optimistic/Cautious/Neutral and support with quotes), and \"🔹 Capex / Risk / Guidance Highlights\".",
    "risks_uncertainties": "List the key risks or uncertainties based on the concall text. Categorize them under these exact Markdown headings if possible: \"Execution Risks\", \"Demand-side or Macro Risks\", and \"Regulatory / External Risks\".",
    "prompt_set": "Based on the provided concall text, generate 3-5 company-specific, smart, and non-generic prompts an investor could ask an LLM to explore further."
}
