"""
report_generator.py — Final Report Generation Node
=====================================================
Produces an equity research-style projection report in Markdown.

Includes:
  - Executive summary
  - Revenue projections table with CAGR
  - Expense projections
  - Below-the-line (EBITDA → EPS waterfall)
  - Key assumptions table with sources & override markers
  - Risk factors & caveats
"""

from __future__ import annotations

import json
from typing import Any, Dict

from langchain_core.messages import HumanMessage, SystemMessage
from projections.llm_providers import get_chat_model


REPORT_SYSTEM_PROMPT = """You are a senior equity research analyst writing a financial projections report.

Write a professional, well-structured Markdown report. Follow this EXACT structure:

# Financial Projections: {company_name}

## Executive Summary
(2-3 paragraph overview of the company, projection methodology, and key takeaways)

## Revenue Projections
(Table with: Line Item | Base Year | Year 1 | Year 2 | Year 3 | CAGR)
(Format numbers as ₹X,XXX Cr)

## Expense Projections
(Table with: Line Item | Base Year | Year 1 | Year 2 | Year 3 | Method)

## P&L Waterfall
(Table with: EBITDA | EBIT | PBT | Tax | PAT | EPS for each projected year)
(If any of these are available from the projection data)

## Key Assumptions
(Table with: Line Item | Growth Rate / Method | Source | Analyst Override?)
(Mark analyst-overridden items with ✅, others with ❌)

## Scenario Analysis
(Summarize bull/base/bear driver deltas and most sensitive assumptions)

## Backtesting & Reliability
(Summarize historical consistency checks and forecast error metrics)

## Assumption Audit Trail
(List high-impact assumptions with source citations and transformation logic)

## Methodology Notes
(Brief notes on how assumptions were generated)

## Risk Factors & Caveats
(3-5 key risks)

## Disclaimer
(Standard projection disclaimer)

Rules:
1. Use ₹ Crores for all values
2. Round to 2 decimal places
3. Include CAGR for all multi-year items
4. Mark analyst-overridden assumptions clearly
5. Cite sources where available
6. Use proper Markdown table formatting"""


async def report_generator_node(state: Dict[str, Any]) -> Dict[str, Any]:
    """
    Generate the final equity research-style projection report.
    """
    company = state.get("company_name", "Unknown Company")
    projection = state.get("multi_year_projection", {})
    assumptions = state.get("locked_assumptions", state.get("draft_assumptions", {}))
    validation = state.get("validation_result", {})
    business_ctx = state.get("business_model_context", {})
    deviation_flags = state.get("deviation_flags", {})
    qa_history = state.get("qa_history", [])
    scenario_analysis = state.get("scenario_analysis", {})
    backtest_metrics = state.get("backtest_metrics", {})
    assumption_provenance = state.get("assumption_provenance", {})

    print(f"\n{'='*60}")
    print(f"📄 REPORT GENERATOR: {company}")
    print(f"{'='*60}")

    # Build the report context
    context = {
        "company_name": company,
        "projection_data": projection,
        "assumptions": assumptions,
        "validation": validation,
        "business_overview": {
            "core_business_model": business_ctx.get("core_business_model", ""),
            "industry": business_ctx.get("industry_classification", ""),
            "competitors": business_ctx.get("top_competitors", []),
            "risk_factors": business_ctx.get("risk_factors", []),
        },
        "deviation_flags": deviation_flags.get("assumption_vs_guidance", []),
        "tone_warnings": deviation_flags.get("tone_warnings", []),
        "scenario_analysis": scenario_analysis,
        "backtest_metrics": backtest_metrics,
        "assumption_provenance": assumption_provenance,
        "analyst_interactions": {
            "qa_count": len(qa_history),
            "last_questions": [q.get("question", "") for q in qa_history[-3:]] if qa_history else [],
        },
    }

    prompt = f"""Generate a comprehensive financial projections report for {company}.

PROJECTION DATA AND CONTEXT:
{json.dumps(context, indent=2, default=str)[:10000]}

Write the full report following the structure in your instructions.
If projection_data is empty, note that and focus on summarizing the assumptions.
Use proper Markdown formatting throughout."""

    llm = get_chat_model("deepseek", temperature=0.3)

    response = await llm.ainvoke([
        SystemMessage(content=REPORT_SYSTEM_PROMPT.format(company_name=company)),
        HumanMessage(content=prompt),
    ])

    report = response.content.strip()
    report_lines = report.count("\n") + 1

    print(f"  ✅ Report generated: {report_lines} lines, {len(report)} chars")

    # Add a metadata footer
    metadata_footer = f"""

---
*Report generated by NOVUS Financial Projections Engine v2*
*Base year: {assumptions.get('base_year', 'N/A')}*
*Projection horizon: {assumptions.get('projection_horizon_years', 3)} years*
*Validation: {validation.get('total_flags', 0)} flags ({validation.get('critical_count', 0)} critical)*
*Scenario set: {scenario_analysis.get('labels', [])}*
*Backtest items evaluated: {backtest_metrics.get('items_evaluated', 0)}*
*Assumption source coverage: {assumption_provenance.get('source_coverage_ratio', 0.0):.1%}*
*Analyst Q&A: {len(qa_history)} interactions*
"""
    report += metadata_footer

    return {"final_report": report}
